# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=flowerary
mod_name=Flowerary
mod_license=MIT
mod_version=1.1.0
mod_group_id=com.github.mnesikos.flowerary
mod_authors=LDShadowLady, anar4732, Mnesikos, SnazzyGator
mod_description=This mod allows you to cross-pollinate vanilla flowers to create different flowers in a variety of colours.\n\nCraft an empty pollen jar to begin, use it to right-click a vanilla flower to collect pollen.\nTransfer the pollen onto another vanilla flower to receive seeds.\nThe seeds can be planted and farmed like vanilla crops.\nOnce they are fully-grown you can harvest the flowers to place elsewhere.