modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="acmc" #mandatory
version="${file.jarVersion}" #mandatory
displayName="LDShadowLady's Flower Breeding Again" #mandatory
authors="LDShadowLady, anar4732" #optional
description='''
This mod allows you to cross-pollinate vanilla flowers to create different flowers in a variety of colours.

Craft an empty pollen jar to begin, use it to right-click a vanilla flower to collect pollen.

Transfer the pollen onto another vanilla flower to receive seeds.



The seeds can be planted and farmed like vanilla crops.

Once they are fully-grown you can harvest the flowers to place elsewhere.



This mod also contains some candles, which are crafted with a clay block, dye and string. They can be stacked like sea pickles.
'''